### ISSUE TITLE
Tapping Back from the talk detail closes the whole app

### ISSUE THREAD

**Issue by asfalcone** [Droidcon-Boston/conference-app-android#1]
The agenda view flashes, then you're at the home screen

Nexus 5X, Android 7.1.2

**Comment by kenyee** [comment]
also, when you background, then restore the app, it returns to the agenda screen

**Comment by emezias** [comment]
Set the detail screen fragment into the backstack. Now the app will return
to the agenda after opening the speaker page.

Return from recent seems fine. Same as if you back to exit the app. There
are bugs staying in the app that are more important to fix.

**Comment by kimj** [comment]
fixed
