### ISSUE TITLE
Design: Update themes & images for 2019

### ISSUE THREAD

**Issue by n8ebel** [Droidcon-Boston/conference-app-android#106]
# To Do
- [x] update theme colors
- [x] update splash screen image
- [x] update drawer image
- [x] update icon
- [ ] change typography?

# Current Colors
- "colorPrimary"         #090909
- "colorPrimaryDark" #000000
- "colorAccent"          #B1EF36

# Current icon, splash screen, drawer assets
[droidconbos18_assets.zip](https://github.com/Droidcon-Boston/conference-app-android/files/2775836/droidconbos18_assets.zip)

**Comment by anandwana001** [comment]
Can we have different fonts to make text looks more smooth than the default?
example - [Rubik Regular](https://www.fontsquirrel.com/fonts/rubik)

**Comment by n8ebel** [comment]
@anandwana001   Updating the typography is certainly something we can look at 👍

**Comment by n8ebel** [comment]
@imanserag I've updated the issue description with the colors and assets we currently have for the icon, splash screen, and drawer.

**Comment by imanserag** [comment]
I've been uploading things to zeplin. Please let me know your email and which team you want to be added to and I can invite you.
