### ISSUE TITLE
Conference feedback

### ISSUE THREAD

**Issue by n8ebel** [Droidcon-Boston/conference-app-android#118]
provide users with the means to provide feedback from within the app

- speaker feedback
- conference feedback

**Comment by n8ebel** [comment]
Previous disscusion from Aniket:

Might be wildly different from what you imagine for speaker feedback, however, what if there were up/down buttons and attendees could tap them, only during the talk, multiple times, depending on how much they liked or disliked some section.
This could be given to speakers synced with the video of their talk as aggregate feedback.
Better with a physical device, possible with the phone. What do you all think of the idea?

**Comment by ericmaxwell2003** [comment]
Proposed must have feature for beta 2.  (Thinking to break this down into a few smaller stories).  Will discuss in Jan 12, status call.

As a conference attendee, I want to be able to go to a session details screen, launch a speaker session feedback form, fill it out and submit.

App AC
- Question Types: Scale of 1-5 questions, yes/no, text input (minimal text input)
- Wizard style, only 1 question at a time.
- Wizard should show progress or N of M to the user.
- Survey should be "offline first".  Meaning that the users should be able to take and submit the survey even if network connection dips.
- User should be able to resubmit survey results, if they like, but only a single survey result should come from each user. (not sure if that's possible if we don't know an email or some key, but nice to have.)
- When user submits a survey, results should be stored locally and synchronized to the backend.  (I think firebase already supports this behavior)

Backend AC
- As part of down sync from server (where sessions, speakers, etc.) are downloaded, updated survey questions should also downloaded.
- The backend should be able to export results into a medium that we can organize and give to speakers.(That last requirement is pretty nebulous.  I didn't want to tie to a specific solution, but to give more context, I was thinking that the backend could have a batch job or manual job that pulls survey results out of firebase  (or wherever) stored and dumps each survey result into an csv file named for the appropriate session.  This would all go in the same output directory.  

For example: 
<output>/survey_results/<authorname>_<session_name>_feedback.csv

**Comment by n8ebel** [comment]
Following up on @ericmaxwell2003 's great breakdown above:

Since we are shorter on time, I think we could simplify the feedback form to a single screen that asks for a 1-5 star rating and a free-form "notes" screen

Collecting this feedback in Firebase would simplify the implementation quite a bit.
- if a session has a unique id in Firebase, then we could likely store a feedback list for each session as a separate node in the db . (wouldn't be attached directly to the session object, but related to it via the id)
- i think pulling the data back out of the db for analysis could take a slightly lower priority since its only useful after the event when we have more time available.  Ideally, it would be great to have a script that could spit out aggregated data for each session

**Comment by AdamMc331** [comment]
I would be happy to help in some capacity. I may have time tonight once I wrap up search, but if I'm unable to get to it I'll have time this week to review if someone else takes it on.

**Comment by AdamMc331** [comment]
Are we collecting feedback per session? This is not conference feedback, right? 

So the feedback CTA would go somewhere on the detail screen, possibly in a menu?

**Comment by n8ebel** [comment]
> Are we collecting feedback per session? This is not conference feedback, right?
> 
> So the feedback CTA would go somewhere on the detail screen, possibly in a menu?

I believe we were thinking of this as "session feedback" where the CTA would be on the session detail page, yes.

**Comment by kenyee** [comment]
this is per session feedback....basically dump it into the user's profile data in some format into a JSON structure we can agree on that will handler everything.  The Admin SDK can in theory read anything in the DB (but I'm still getting auth issues w/ their setCredentials API not showing up at compile time) but if worse comes to worse, we can export out the entire users node manually and postprocess it.
Maybe something like
users/<userid>/sessionFeedback/{ sessionId1: {rating: 1-5, comments: <string>}, sessionId2:... }

**Comment by n8ebel** [comment]
that sounds like pretty much what I had in mind

**Comment by AdamMc331** [comment]
So I haven't hooked anything up to firebase, but I did start building out a simple UI. Any thoughts so far? Off the top of my head I might change the comment box to be 2/3 lines so it helps encourage people to write a little more. Wasn't sure if a title on the dialog was necessary. 

![RatingDCBOS](https://user-images.githubusercontent.com/9515997/54073935-d6d0aa80-425a-11e9-832b-309a6d2fd92d.gif)

**Comment by kenyee** [comment]
Added PR that handles firebase storage of feedback: 
https://github.com/Droidcon-Boston/conference-app-android/pull/162
This can be closed when the PR is merged.

**Comment by kenyee** [comment]
PR has been merged...
