### ISSUE TITLE
Jump to current time when viewing your schedule

### ISSUE THREAD

**Issue by n8ebel** [Droidcon-Boston/conference-app-android#120]

**Comment by ericmaxwell2003** [comment]
First need to verify existing functionality.  Eric to verify this, working with others to figure out the best way to test.

**Comment by ericmaxwell2003** [comment]
I don't see this functionality.
- I tested via setting my simulators time to 3/26/2018 at 12:30 EST.
- Then just to double check added a quick hack to change `ScheduleEvent` start and end times inside of the `AgendaDayFragment.dateListener`, to today and tomorrow at the same times.

Neither seemed to have an effect on the schedule.  Both tabs in the viewPager started at the beginning of the day.  

I also took a quick glance and didn't see any code that would auto scroll down.  But I could totally be missing something :-) 

CC @kenyee @kimj

**Comment by kenyee** [comment]
Yep, you're right...only does this:

```

            // set current day to second if today matches
            val today = Calendar.getInstance()
            val dayTwo = Calendar.getInstance()
            dayTwo.set(2018, Calendar.MARCH, 27)
            if (today == dayTwo) {
                viewpager.currentItem = 1
            }
```

The adapter also will add highlights as needed to indicate whether the session is in the past.

**Comment by ericmaxwell2003** [comment]
Functionality complete.  Just need to add some more testing around it.

Demo:
https://drive.google.com/open?id=1n4OFBDYhZAZcXmUP-6v_sHdQfPkEmU63
