### ISSUE TITLE
Push notifications for important events & updates

### ISSUE THREAD

**Issue by n8ebel** [Droidcon-Boston/conference-app-android#130]

**Comment by n8ebel** [comment]
related to #123

**Comment by fetching** [comment]
I think this is a Must Have.

**Comment by kenyee** [comment]
This is already in the app..I added FCM support last year

**Comment by n8ebel** [comment]
@kenyee Would you mind adding something to a wiki page or to the README about how the push notification process is currently set up?

There had been some previous questions around what types of events were supported, how they were triggered, etc

If we can get a better idea of what's already supported, we can decide what, if anything, we want to add :-)

**Comment by kenyee** [comment]
task for ken: update Readme w/ docs on how this works

**Comment by kenyee** [comment]
Used the wiki instead..made more sense to put it there than the Readme:
https://github.com/Droidcon-Boston/conference-app-android/wiki

This can be closed probably unless we need some more automated way of sending messages (maybe some sort of "admin" mode in the app) to all users?  Or just use the Firebase console :-)

**Comment by n8ebel** [comment]
thanks @kenyee  👍 

I think we can close this out
