### ISSUE TITLE
Allow users to share sessions to Twitter

### ISSUE THREAD

**Issue by AdamMc331** [Droidcon-Boston/conference-app-android#133]
Tangentially related to #112, I was thinking about how people at conferences often send out tweets like:

> I really enjoyed [TALK_TITLE] by @[SPEAKER_HANDLE]!

Which is cool because it can spark discussions on Twitter and I'm sure speakers would appreciate it. 

Here's some initial SO search that can be used to do this: https://stackoverflow.com/a/14664917/3131147

Some things we would need to finalize: 

- What is the pre populated Tweet copy? 
- What will the UI be to prompt this? I like the idea of putting a little Twitter icon near the bottom of a session with text like "Enjoy this talk? Let your followers know!" and clicking on this CTA will launch the intent.

**Comment by AdamMc331** [comment]
I agree that we should add the conference handle. Definitely an extra benefit. :)

**Comment by AdamMc331** [comment]
I really like this! My peppy personality wants to add an exclamation point at the end (after the user name) but I think that's just me hahaha. 

If the speaker doesn't have a twitter handle will we just populate their name? 

I like that it launches straight into twitter and gives people a chance to modify it or add a picture. I don't think we can do this, but do speaker sessions have links for them that we could add to the tweet? Like a link to the session and description? That might be out of scope.

**Comment by AdamMc331** [comment]
Hey just bumping this. Is there anything I could do to help? I think the second portion of my last message was out of scope, but hopefully we consider the case where the speaker doesn't have a twitter handle.

**Comment by n8ebel** [comment]
@djain2405   This is looking great 👍    I have the same thought/question as @AdamMc331 : could we possibly include a link to the individual session and/or speaker profile so there's additional related content to include?

**Comment by djain2405** [comment]
Sorry Just saw this message. Will test it tomorrow and update by tomorrow end of the day for sure!

**Comment by n8ebel** [comment]
@djain2405  Did you get a chance to try that out?
