### ISSUE TITLE
Droidcon vs. DroidCon

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#14]
Epic work here folks!

I'm noticing that we sometimes reference "Droidcon" and sometimes "DroidCon".

For example, app_name in strings.xml uses "DroidCon":

<string name="app_name">DroidCon Boston</string>

But elsewhere in text such as FAQ's and on the web site we use Droidcon. 

A quick search seems to indicate it should be "Droidcon". Should we update the app?

**Comment by emezias** [comment]
good point - the Google Sheet has most of the content and we can make sure it's consistent

**Comment by emezias** [comment]
Updated text in the spreadsheet to be consistent.
