### ISSUE TITLE
Animated Loading Icons

### ISSUE THREAD

**Issue by n8ebel** [Droidcon-Boston/conference-app-android#141]
Create an animated loading screen with the droid dancing. 
Utilize Lottie / Bodymovin from AE to do said animation.

**Comment by imanserag** [comment]
Here is the xml file, json file, along with the html file if we want to put it on the website? 


[DancingDroid.zip](https://github.com/Droidcon-Boston/conference-app-android/files/2812608/DancingDroid.zip)
