### ISSUE TITLE
Pull in the 2019 data from slidesup

### ISSUE THREAD

**Issue by n8ebel** [Droidcon-Boston/conference-app-android#155]

**Comment by kenyee** [comment]
this works in manual kotlin script form now...still have to put the script somewhere to have it run periodically

**Comment by n8ebel** [comment]
@kenyee do you think we can close this ticket now that data has been pulled in?

**Comment by kenyee** [comment]
data has been pulled in..can run script to do pulls but need a place to put it to run from a cron job
