### ISSUE TITLE
Hamburger menu replaced by Back Arrow after browsing

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#16]
1. When I open the app initially I have the hamburger menu in the top left corner:

![hamburgermenu](https://cloud.githubusercontent.com/assets/15278837/24685158/b6eba6ea-1979-11e7-8f20-1b1570c95b34.png)

2. From Agenda, tap any speaker to open their profile.

3. Tap back arrow in the top left to go back.

4. The hamburger menu is now replaced by the Back Arrow.

![backarrow](https://cloud.githubusercontent.com/assets/15278837/24685196/f24b84a8-1979-11e7-82c6-84253b52c516.png)

5. The back arrow at this point functions as the hamburger menu.

**Comment by emezias** [comment]
The speaker detail page was doing that because we want to set that page as a child page with the up arrow. For now, the weird icon change is fixed in master.
