### ISSUE TITLE
Reference to "Kotlin.unit" appended to speaker name in Agenda detail

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#167]
The detail screen for the Community Addition talk by Giorgio has a "Kotlin.Unit" reference appended to Giorgio's name, Eliza's name and perhaps other speaker names.

See attached screenshot for example.

![KotlinUnit](https://user-images.githubusercontent.com/15278837/54731760-77ca3a00-4b66-11e9-8b94-021508ee2629.jpg)

**Comment by djain2405** [comment]
@fetching if you can check it on the latest build, let me know if its working fine :)

**Comment by fetching** [comment]
@djain2405  looks great!  The Kotlin.Unit references are all gone. 💯
