### ISSUE TITLE
Agenda -> Day 1 -> 11:30am slot has no data and location is null

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#168]
There is currently no data in the Agenda view or the detail view for the Agenda -> Day 1 -> 11:30am talk slot and the location is currently null ("at null").  See attached screenshot.

![NoData](https://user-images.githubusercontent.com/15278837/54731907-3dad6800-4b67-11e9-8876-3cba6b444bc1.jpg)

**Comment by n8ebel** [comment]
@GiorgioNatili  @kenyee   I'm assuming this is a data issue?

**Comment by fetching** [comment]
@n8ebel the last data sync from SlidesUp must have fixed this issue because I don't see it any more. Closing.
