### ISSUE TITLE
Speaker photo image covers a portion of the talk title text for a long title

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#169]
In the case of a longer title the title in the talk details screen is slightly covered by the speaker's image.  See the attached screenshots for examples.  

In addition to the screenshot examples these talks share the same issue:

- Lyla Fujiwara
- Anton Spaans
- Jamie Lynch
- Stephen Magill

Is it possible to fix it so that the title is not obscured by any other object?

![ImageOverText](https://user-images.githubusercontent.com/15278837/54732168-afd27c80-4b68-11e9-8c69-57624f82df6d.jpg)

![ImageOverTitleText2](https://user-images.githubusercontent.com/15278837/54732416-0c826700-4b6a-11e9-8b90-946ba6940b47.jpg)

![ImageOverTitleText3](https://user-images.githubusercontent.com/15278837/54732372-c4fbdb00-4b69-11e9-8b5e-0d0d8916c64f.jpg)

**Comment by kenyee** [comment]
this should be fixed...used an autosizing textview limited to two lines

**Comment by n8ebel** [comment]
sounds good @kenyee 👍
