### ISSUE TITLE
Clicking Information icon on Vejigantes restaurant in FAQ's will crash the app

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#17]
1. Open the app.

2. Choose FAQ from the hamburger menu.

3. Scroll down to the Vejigantes, Puerto Rico Food entry.

4. Tap the Information icon.

5. The app crashes.

6. (If you return to this same section you'll see that the Banyan Asian Fusion Information icon below Vejigantes opens up to their web site as expected. )

**Comment by emezias** [comment]
FAQ links should all be fixed in the latest beta
