### ISSUE TITLE
Agenda -> Day 1 -> 4:00pm slot has no information yet

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#170]
Agenda -> Day 1 -> 4:00pm slot has no information yet.  We'll need to populate the data source with the information.

**Comment by n8ebel** [comment]
@fetching  Is this something you were able to find/fix/verify in SlidesUp?

**Comment by fetching** [comment]
@n8ebel  the Agenda->Day 1->4:00pm slot has now been populated with talk data. Closing.
