### ISSUE TITLE
Talk title is not proper-cased and some talks have a period at the end

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#172]
The title of the talk in this screenshot is not proper cased.  Only the first letter of the first word of the title is uppercased.  Most of the titles are proper cased and look better. 

Additionally some talk titles have a period at the end but I think it should be omitted?

I would suggest that we change titles to be proper cased and omit any ending period.

(Or I guess we can discuss what the convention should be :-)) 

![TitleCasing](https://user-images.githubusercontent.com/15278837/54733100-15753780-4b6e-11e9-9658-5006b4a4e3e0.jpg)

**Comment by n8ebel** [comment]
@GiorgioNatili  @kenyee    Does it make sense to go in and cleanup the SlidesUp data to make the title formatting consistent?  Is that a ton of work?

**Comment by kenyee** [comment]
This is a Slidesup data issue AFAIK

**Comment by n8ebel** [comment]
@fetching  Is this something you were able to find/fix/verify in SlidesUp?

**Comment by fetching** [comment]
@n8ebel I can go in to SlidesUp and update the data. Shall we go with proper casing?  I think it looks best because otherwise the title will look like a sentence. I will go ahead with it.

**Comment by fetching** [comment]
OK @n8ebel I cleaned up a few talks. I stand corrected on proper-casing which may crowd the small real estate. Sorry for the waffling. We'll pick up the changes on the next data sync. Closing.
