### ISSUE TITLE
Typo in one of the names

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#173]
In his speaker bio and talk Sean McQuillan's name is spelled as "McQuillian" with an extra "i" in his last name.  We need to update the data to the proper spelling:  McQuillan

Here is his Twitter feed for reference: https://twitter.com/objcode

**Comment by n8ebel** [comment]
great catch @fetching !!!

**Comment by fetching** [comment]
Fixed in SlidesUp.  Change will be seen in next sync. Leaving this ticket open for final testing after sync.

**Comment by fetching** [comment]
Ken sync'ed the SlidesUp data and I see the change now.
