### ISSUE TITLE
Speaker images overlapping each other when there are two speakers

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#174]
When there are two speakers for a talk the two speaker images are overlapping each other. Is it possible to put some space between them?

Here is one example but I think the overlapping occurs for any talks with two speakers:

![SpeakerImagesOverlapping](https://user-images.githubusercontent.com/15278837/54733478-46566c00-4b70-11e9-9005-eba3869d270b.jpg)

**Comment by kenyee** [comment]
that was intentional from last year AFAIK

**Comment by fetching** [comment]
No problem, if its a design decision then that's fine. They all do line up the same way and are consistent across talks with 2 speakers.

**Comment by n8ebel** [comment]
sounds like this is working as expected.  will close this for now
