### ISSUE TITLE
CoC does not match web site - may be from 2018

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#177]
The Code of Conduct displayed in the app does not currently match what I see on the web site. I think the app may be displaying the 2018 CoC? 

Importantly, the CoC in the app references a contact email address that I believe is no longer in use.

**Comment by fetching** [comment]
I'm attaching a chunk of HTML with the 2019 CoC in it on one line. We can replace the existing value in Firebase and test to see if formatting is good.

**Comment by kenyee** [comment]
updated firebase

**Comment by fetching** [comment]
@kenyee  updated Firebase for us. Now the content matches what is on the web site. If we fix other bugs we can circle back and touch-up the formatting further if we wish.
