### ISSUE TITLE
Logged in to app but received an error

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#179]
I tried logging in to the app using the Log In menu item in the Navigation Drawer but got an error.  See this screenshot for the error message:

![LoginError](https://user-images.githubusercontent.com/15278837/54734296-ef06ca80-4b74-11e9-95ca-79eb88b20cf7.jpg)

**Comment by CCorrado** [comment]
As discussed in slack, this is due to not having your SHA1 in the firebase console.

To get your SHA1 added, follow the steps and you can DM me or another person on the team with access to firebase. https://developers.google.com/android/guides/client-auth
