### ISSUE TITLE
Deselecting a talk from within My Schedule, press Back, list does not update

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#181]
When inside My Schedule and deselecting a talk and pressing Back the My Schedule list is not being updated.

Steps to reproduce the scenario:

1. Go to Agenda
2. Click on either Day
3. Tap any talk to open details
4. Star that talk to add it to My Schedule
5. Press Back
6. The Agenda shows the orange star indicating you chose this talk for My Schedule
7. Go to My Schedule
8. Tap the same talk to open the details
9. Tap the star to remove this talk from My Schedule. You'll get a toast indicating the talk has been removed.
10. Press Back
11. The talk still shows with an orange star.  Perhaps we need a listener here to listen for changes made?
12. Go to Agenda. The talk is no longer has an orange star, which is expected behavior.
13. Go back to My Schedule. The talk is no longer listed, which is expected behavior.

**Comment by kenyee** [comment]
@fetching please retest...
