### ISSUE TITLE
App is crashing upon Logout

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#182]
Log In is working now that my SHA1 is added to Firebase (💯). And the Navigation Drawer menu item changes from Log In to Log Out when I'm logged in. (👍)

However, Log Out is consistently crashing on my phone. I don't have a stack trace as I'm not connected to Android Studio right now. Maybe someone has received a crash report with details?  I have a Samsung Galaxy J7 phone.

**Comment by CCorrado** [comment]
I'll take a look!

**Comment by CCorrado** [comment]
I'm not able to reproduce, and not seeing a stack trace for the past 7 days in Crashlytics :( 

I did these steps:
1. Log in with my gmail
2. Favorite a few talks on days 1 and 2.
3. Force Quit the app
4. Reopen the app
5. Notice data is still there
6. Log out
7. Notice data is still there
8. ADB clear app data
9. Open the app
10. Notice data is gone
11. Log in

The app never crashed for me. I'm on develop commit **4c5a6aa** which @n8ebel recently updated on 3/25 around 2PM. Can you try maybe updating to the latest version? Worried more that we didn't get the stack trace in crashlytics...

**Comment by CCorrado** [comment]
@fetching are you still seeing this issue? I don't have a galaxy to test on, although I might still have my S4 if I can find it!

**Comment by fetching** [comment]
@CCorrado  I just logged in and out 3x and I didn't see the issue. I think we can close it!

**Comment by fetching** [comment]
I'm not seeing this issue any more so will close it.
