### ISSUE TITLE
Speaker's details page has only @ without a location

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#183]
I notice that Alex Sullivan's Speaker (and others, see next comment) bio has an "@" for where he works but there is no data attached to it. I'm not sure if he wishes to omit it but in that case can we also omit the @ symbol?  It looks a little empty around the @.  See attached screenshot.

![JustAt](https://user-images.githubusercontent.com/15278837/54799214-aa416900-4c32-11e9-9c57-58753af2e42d.jpg)

**Comment by fetching** [comment]
I noticed that Carmen Gonzalez has the same issue.

**Comment by fetching** [comment]
I've updated most of the speakers and was able to verify they look good now that Ken sync'ed SlidesUp data. A few remaining speakers have messages from me to send me their title and company.

**Comment by n8ebel** [comment]
sounds great @fetching   do you think we can close this one out then?

**Comment by fetching** [comment]
Yes @n8ebel  I have contacted the remaining few so can update SlidesUp when they get back to me. I agree we should close the ticket on our side so I'm going to do so.
