### ISSUE TITLE
The "25min talk" placeholder cannot be added to Agenda

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#184]
This may be expected behavior but I want to report it just in case.

There is a talk at 4pm on Day 1 that is currently a placeholder named "25min talk". 

I'm unable to "star" this talk and add it to My Schedule.  Tapping the star only ever toasts me to say "Removed from My Schedule".

We can close this Issue if it's expected behavior.

**Comment by n8ebel** [comment]
@fetching  Is this something you were able to find/fix/verify in SlidesUp?

**Comment by fetching** [comment]
The Day 1 -> 4:00pm placeholder is now gone and real talks are in the agenda now (and I can add them to My Schedule).  Closing.
