### ISSUE TITLE
Splash screen stays around after app has launched

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#185]
The splash screen is hanging around after the app has launched. If I start the app and tap the Recents button I see two activities running.

Looks like its a side effect of MainActivity having launchMode=singleTask in AndroidManifest:

https://github.com/Droidcon-Boston/conference-app-android/blob/develop/Droidcon-Boston/app/src/main/AndroidManifest.xml#L32

Setting launchMode=standard or moving launchMode=singleTask to SplashActivity in AndroidManifest results in the splash screen finishing though I'm not sure yet if something else will break if MainActivity is not singleTask.

**Comment by n8ebel** [comment]
@kenyee  @GiorgioNatili   do either of you have any historical insights into this?

**Comment by kenyee** [comment]
Sounds like a bug...don't think we ever noticed this last year.

**Comment by fetching** [comment]
@kenyee  I would suggest we move to standard or move singleTask to the Splash Screen activity and we can observe any changed behavior with our next test phase.

**Comment by n8ebel** [comment]
@fetching @kenyee It looks like it was introduced in this commit 70ae7d07af49261a4b45f7997284d2044984aa4b to avoid creating multiple activities if notifications were clicked multiple times.

I wonder if `singleTop` might do the trick.  In some quick testing it solves the splash screen issue described here, and it seems like it would still work for the original notification issue (though I haven't verified that)

**Comment by n8ebel** [comment]
@fetching @kenyee  I created #193 for the proposed changes.  @fetching can you test this please.

**Comment by fetching** [comment]
I see now the design decision relates to notifications, which I haven't looked at in testing. I agree singleTop should suffice as long as the data is refreshed properly after tapping the notification. Will need to do a test run of notifications when ready.

**Comment by fetching** [comment]
@n8ebel  @kenyee  splash screen is no longer hanging around

I've tested navigating all around the app and there is still only one MainActivity and only one Droidcon Boston activity when tapping Recents. I'll need to test Notifications this weekend.

```
$ ~/Library/Android/sdk/platform-tools/adb shell dumpsys activity activities | sed -En -e '/Stack #/p' -e '/Running activities/,/Run #0/p'
  Stack #1:
    Running activities (most recent first):
      TaskRecord{b1f3bd1d0 #5004 A=com.mentalmachines.droidcon_boston U=0 StackId=1 sz=1}
        Run #0: ActivityRecord{3538f04d0 u0 com.mentalmachines.droidcon_boston/.views.MainActivity t5004}
  Stack #0:
    Running activities (most recent first):
      TaskRecord{f2cd856d0 #4948 A=com.android.systemui U=0 StackId=0 sz=1}
        Run #1: ActivityRecord{c5d6d8ad0 u0 com.android.systemui/.recents.RecentsActivity t4948}
      TaskRecord{a07bc24d0 #4908 I=com.sec.android.app.launcher/com.android.launcher3.Launcher U=0 StackId=0 sz=1}
        Run #0: ActivityRecord{a461078d0 u0 com.sec.android.app.launcher/.activities.LauncherActivity t4908}
```
