### ISSUE TITLE
Feedback stars on talks is obscured by speaker image

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#187]
The feedback stars are a great feature!  However, I notice that speaker images may sometimes be covering them, which affects selecting and seeing the stars. See attached screenshot for example.

FYI: this issue has similarities to: https://github.com/Droidcon-Boston/conference-app-android/issues/169

![StarsCoveredByImage](https://user-images.githubusercontent.com/15278837/54872034-1e475280-4d94-11e9-9f81-9ed8784bd9da.jpg)

**Comment by kenyee** [comment]
Seems like limiting the title to two lines and using a fit text view would fix this

**Comment by fetching** [comment]
This is fixed now.
