### ISSUE TITLE
Need Social Events page or link

### ISSUE THREAD

**Issue by asfalcone** [Droidcon-Boston/conference-app-android#19]
Clicking on `5:30 on 4/11 BOF, PANEL, CLOSING PARTY` should open a new view with info from here:
http://www.droidcon-boston.com/events-info/ or at least open that URL

**Comment by emezias** [comment]
@kenyee Does this look easy to fix?

**Comment by kenyee** [comment]
open's that URL in a web browser when you click on it...there's no data for this even in the DB/spreadsheet.
