### ISSUE TITLE
Need to test Notifications

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#194]
I hope its OK to create an Issue to track testing of Notifications. I can pair with whoever has ability to create the notifications and we can pick a time to test them.

In particular, we changed launchMode=singleTask to launchMode=singleTop for MainActivity so we need to be sure we don't leak activities.

**Comment by n8ebel** [comment]
@fetching I think @kenyee  is probably the right person to pair with on notifications.

There is a small wiki entry around our notifications here: https://github.com/Droidcon-Boston/conference-app-android/wiki/Push-Notifications

**Comment by fetching** [comment]
Awesome @n8ebel  I see we are using the Firebase Console to send Notifications. I'll get more info from @kenyee .

**Comment by fetching** [comment]
Can close this based on the other ticket regarding notifications testing.
