### ISSUE TITLE
droidconbos handle wraps into text of Twitter feed

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#195]
Looking at the Twitter Feed on my phone it looks awesome!  But I notice that the ending "os" from the @droidconbos Twitter handle wraps into the tweet text and is layer beneath the tweet text.

I'll attach a screenshot from my phone. You can see the "os" in a different font color beneath the word "announce" in the tweet.

I wonder if its possible to widen the feed so that the "os" doesn't wrap?

![TwitterFeed](https://user-images.githubusercontent.com/15278837/55046168-f287cf00-5016-11e9-8048-21131b48e3c2.jpg)

**Comment by sagar-viradiya** [comment]
Noted. Fixing this

**Comment by fetching** [comment]
Great @sagar-viradiya  the @droidconbos text is no longer wrapping!
