### ISSUE TITLE
Speaker image in Agenda Detail is very tiny in at least one case

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#199]
I notice that the speaker photo is very tiny in the Agenda Detail for at least one case.  Can someone take a look?

Also the speaker images in Agenda Detail for Adrian and Carmen's talk also have slightly smaller images compared to other Agenda Detail views.

Here is the example where the image is very tiny:

![ImageIsTiny](https://user-images.githubusercontent.com/15278837/55201491-a87b2680-5199-11e9-82d4-31d99fc133da.jpg)

**Comment by kenyee** [comment]
this has been fixed by using an autosizing textview...please recheck @fetching

**Comment by fetching** [comment]
Voila!  Looks great @kenyee, thanks!
