### ISSUE TITLE
AgendaDetail view for Check-in is missing some info and needs some removed

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#200]
For the Check-In item on the Agenda we have a couple of issues:

1. Description is not displaying any content. Ken and I are talking about it in the chat.

2. The heart to add the Check-In to My Schedule should be hidden since it doesn't have any effect and just toasts.

3. The Twitter icon is floating by itself as there is no shareable data attached to it.  We could hide it perhaps?

See attached screenshot.

<img width="150" alt="Screen Shot 2019-03-29 at 6 15 37 PM" src="https://user-images.githubusercontent.com/15278837/55265528-1a617780-524f-11e9-8b27-35a732dee0db.png">

**Comment by kenyee** [comment]
this has been fixed @fetching ...please retest and close if fixed

**Comment by fetching** [comment]
@kenyee  it looks great, thanks so much for digging in and making it look great!  💯 🥇
