### ISSUE TITLE
Twitter icon is not displayed on my phone for Share this talk to Twitter 

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#205]
I have a Samsung Galaxy J7 and the Twitter icon is not shown on my phone for sharing talk to Twitter. See attached screenshot.

![TwitterIconNotDisplayed](https://user-images.githubusercontent.com/15278837/55278558-38c58280-52e4-11e9-9aa2-28396b35f967.jpg)

**Comment by n8ebel** [comment]
fixed in #206
