### ISSUE TITLE
Speaker images render slowly and have a large Android image as a (large) thumbnail

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#21]
Build number:  I took an Android app update around 9:20pm today 4/5/2017.

I notice that when loading speaker profiles the first time their images sometimes load slowly and the Android image displays. Looks like its the R.drawable.emo_im_cool placeholder for Glide that I'm seeing?

The images do load a little slowly and the transition to and from the Android image is somewhat prominent. Some images are slower than others, probably due to size? 

I made a screencast so you can see what it looked like on my Samsung Galaxy 7 with Wifi enabled but the screencast file format is not supported for attachment here. 

Instead I took a screenshot instead to illustrate what it looks like. So the Android image lingers long enough for me to capture a screenshot (I'm running Visor Chrome extension to capture the screenshot on my MacBook).
![profileimage](https://cloud.githubusercontent.com/assets/15278837/24734153/ea877b02-1a49-11e7-8c33-1e5cd1cf4e3a.png)

Note that after loading the image the first time the image is fast thereafter and no Android image displays, presumably due to caching.

**Comment by emezias** [comment]
There Android images is a placeholder. Previously the photo pooped into place, unexpectedly scrolling the text down under it. This is working as designed. Be cool if you have a replacement image for the placeholder. Where is the bug?

**Comment by fetching** [comment]
Yes, I agree the Android image is a placeholder and its not necessarily a bug bug. I just wanted to share that it lingers perhaps a little long and this image is a little dominant. So we can close this. Great job, Glide is awesome!

**Comment by fetching** [comment]
Oops I'll click Close.
