### ISSUE TITLE
Text for sharing talks via Twitter is being cut off

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#213]
The text for sharing talks via Twitter is being cut off.  Here is what I see on my Samsung Galaxy J7:

![TwitterText](https://user-images.githubusercontent.com/15278837/55283900-532a4b00-533a-11e9-8a1e-15e19496b30e.jpg)

**Comment by fetching** [comment]
I know that in Issue 205 I reported the icon wasn't displaying. And now I'm reporting the text is not fitting.  If it helps we could shorten the text slightly to:  Enjoy this talk? Tell your Followers!

**Comment by n8ebel** [comment]
I changed things yesterday so the text would get cut off instead of the icon.  We could allow multiple lines of text though and just wrap.  It doesn't look the best, but it's at the bottom of the screen and should only be an issue on smaller devices

i'll update it
