### ISSUE TITLE
Bottom half of menu items are off by 1

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#23]
It seems like the bottom menu items are off by 1.  Here are the results that I get currently:

Instagram Too - opens Twitter
LinkedIn N.E. Android Devs - opens our Instagram
Open Twitter - opens Linked In NE Android Devs

The Agenda, Twitter, FAQ and Our Facebook menu items are working correctly.

**Comment by emezias** [comment]
Added contact us to go to form. Fixed order in latest beta
