### ISSUE TITLE
Social icons are all white on Android 4.4.2

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#26]
I notice when running on a Samsung Galaxy 3 running Android 4.4.2 that the social icons are all white (on a lightgrey background)

I see all the icons are now blue on Marshmallow. Not sure if its easy to fix the assets for earlier versions at this point?

**Comment by fetching** [comment]
The icons in the nav drawer are also white except for Contact Us. I can attach a screenshot when I get home.

**Comment by fetching** [comment]
![socialiconsandroid422](https://cloud.githubusercontent.com/assets/15278837/24829365/09cca866-1c3e-11e7-8922-bb52731c13dc.png)


![navdrawerandroid422](https://cloud.githubusercontent.com/assets/15278837/24829366/09ce2c2c-1c3e-11e7-8830-67718fca0566.png)

**Comment by emezias** [comment]
fixing dynamically built selectors now - they need to be bitmap drawables or else the last color filter set sticks to all states
