### ISSUE TITLE
One Twitter profile doesn't open in app for 4.4.2

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#27]
Android 4.4.2:  I notice that for Tyler Nappy the Twitter app doesn't launch when tapping the Twitter icon but it opens as expected for other speakers. Just wondering is there something different about the underlying link as compared to other profiles?

It opens as expected on Marshmallow too.

**Comment by fetching** [comment]
I meant to say that a browser is launched instead of the Twitter app.  Sorry I'm on a phone and can't see how to edit it. :-)

**Comment by emezias** [comment]
not sure, found http://twitter.com in some and https://twitter.com in others. Changed them all to be https. Change will go into version code 8.

**Comment by emezias** [comment]
Closing - the 2017 data is deprecated. We'll see if this comes back in the 2018 speaker profiles.
