### ISSUE TITLE
Firebase icon in agenda seems a little too wide

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#28]
I notice that when tapping the the Firebase agenda item and looking at the abstract the Firebase icon is a little bit too wide and the flame gets cut off. This is on Marshmallow Galaxy J7 and my Android 4.2.2 Galaxy 3.

**Comment by emezias** [comment]
Changing speaker image link for the Firebase code lab to show only the icon
https://lh3.googleusercontent.com/TMqvJdxi8bUMcux_bRQeGUkN4qhSNio1Katx7GSxI5cX7wyuv_nFssaBb1DJ3FcLc0N1OqxpDLy7ln8LXdbeiCS5MwEAr3g=s688

**Comment by fetching** [comment]
Fixed!
