### ISSUE TITLE
Pro Tip has no icon if first FAQ tap;  has an icon later

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#29]
I notice that if I visit the FAQs and go to How To Get Around the first item, Pro Tip from airport does not have an icon. That's perfectly OK since the information is complete as is and no need to tap for more info.

However if I go to Pro Tip after clicking on the Information icons for the previous FAQs then I get an information icon. Tapping it goes to weather service or sometimes Twitter.  It seems to maybe inherit from a previously tapped information icon.

**Comment by fetching** [comment]
"Unfortunately parking will be limited..." FAQ seems to share the same characteristic.

**Comment by emezias** [comment]
This problem was fixed in version code 6
