### ISSUE TITLE
Suggestion to modify text for Quincy Market FAQ

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#31]
Our Quincy Market FAQ entry says "Quincy Market since 1742?"

I would suggest we modify it to be just "Quincy Market" with any "since" with a question mark.

Technically speaking Faneuil Hall is around since 1743:

Faneuil Hall (/ˈfænjəl/ or /ˈfænəl/; previously /ˈfʌnəl/), located near the waterfront and today's Government Center, in Boston, Massachusetts, has been a marketplace and a meeting hall since 1743.

But Quincy Market is around only since 1824:

Quincy Market is a historic market complex near Faneuil Hall in downtown Boston, Massachusetts. It was constructed in 1824–26 and named in honor of Mayor Josiah Quincy

**Comment by emezias** [comment]
A secondary problem is that the app says Quincy Market while the map label says Faneuil Hall! Set the text to say Quincy Market and Faneuil Hall, added in the descriptive paragraph with proper pronunciation from above. Given the diversity of dialects here in the Commonwealth, pronunciation information seems a good thing

**Comment by fetching** [comment]
Fab fix here!  Fixed in v7.
