### ISSUE TITLE
Need to fix typo for movie theatre FAQ

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#32]
We have a tiny typo in our map reference for the AMC Loews Boston FAQ.  

When you tap the icon and launch Google Maps the tag reference says "Leows".  Can we update it to "AMC Loews"?

**Comment by emezias** [comment]
sheet updated, change will be in version code 7

**Comment by fetching** [comment]
I hate to say it but the map says "AMC Leows" instead of "AMC Loews".  If we push another version we can think about including a fix.

**Comment by emezias** [comment]
The 2017 data is deprecated. We'll try to get this right in the new, improved app.
