### ISSUE TITLE
Chat/Slack

### ISSUE THREAD

**Issue by kimj** [Droidcon-Boston/conference-app-android#36]
This is a reminder ticket to setup up slack to add people in as they register with a script or something. If this works maybe provide a link in app if the api supports it.

**Comment by emezias** [comment]
Using Firebase allows the app to remove all dependency on Slack and the mess of administering slack accounts. Android conference attendees already have a Google account that can connect to a chat feature without the friction.
Chat Kit and Firebase Android Chat - https://android-arsenal.com/details/3/3812

**Comment by kimj** [comment]
This is just to remind me that I should find the script that NYC DroidCon used to auto create Slack invites as part of registration. I just put it here because I don't know where else to keep these reminders.

**Comment by redbassett** [comment]
I fully support automatic invitation when an attendee registers as the best option, but when we were talking about this in person, I mentioned [Slackin](https://github.com/rauchg/slackin) (used by a number of code meetups in Boston) or [Slack Invite Automation](https://github.com/outsideris/slack-invite-automation) as a backup solution for attendees to voluntarily register themselves.

**Comment by emezias** [comment]
Problem is a limit on the number of open invitations on a free Slack
channel. Thanks Harry.
