### ISSUE TITLE
2 twitter menu items

### ISSUE THREAD

**Issue by asfalcone** [Droidcon-Boston/conference-app-android#8]
![image](https://cloud.githubusercontent.com/assets/1848683/24638015/5136f4b0-18b3-11e7-9419-9875243c6b97.png)

**Comment by emezias** [comment]
One is an in app, read only list to show Droidcon, DroidconBoston and
DroidconBos hashtags.

The other is a contact us link.

This is working as designed.

**Comment by emezias** [comment]
The second Twitter menu item is highlighted to indicate it is a contact link. It's what we got to do on short notice...
